const menuList=[
    {
        title:'首页',
        key:'/home',
        icon:'home',
    },
    {
        title:'系统管理',
        key:'/system',
        icon:'home',
        children:[
            {
                title:'用户管理',
                key:'/',
                icon:'home', 
            },
            {
                title:'客服管理',
                key:'/',
                icon:'home', 
            },{
                title:'供电所管理',
                key:'/',
                icon:'home', 
            },{
                title:'台区经理管理',
                key:'/',
                icon:'home', 
            }
        ]
    },
    {
        title:'基础数据',
        key:'/home',
        icon:'home',
    },
    {
        title:'用电报修管理',
        key:'/home',
        icon:'home',
    },
    {
        title:'停电信息管理',
        key:'/home',
        icon:'home',
    },
    {
        title:'台区监测系统',
        key:'/home',
        icon:'home',
    },
    {
        title:'内部意见管理',
        key:'/home',
        icon:'home',
    },
    {
        title:'用户留言管理',
        key:'/home',
        icon:'home',
    },
    {
        title:'台区告警管理',
        key:'/home',
        icon:'home',
    },
    {
        title:'小夜灯告警管理',
        key:'/home',
        icon:'home',
    },
]
export default menuList